key: ᬅᬓ᭄ᬱᬭ #init aksara key
model_path: example/model  #init model dir
module_name: my-app  #init module gomod
models:
    Branch: #Example Model1 Name
      module: branch
    Company: #Example Model2 Name
      module: company
meta:
  result_path: module
  main_dir: example
  template: ~main_dir~/unclebob/templates
   #you can fill other static meta here

#jobs is queue of generator file
jobs:
  - name: main #job name
    dir:  ~main_dir~/app1 #directory generate file
    template: ~template~/main.text #template for generate file
    file_name: main.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    generate_in:  #replace code @GenerateIn [key] in file with this job
    tags:
      #list of tag, that can executed by group of tag
      - init
      - structure
      - main

  - name: new route in main #job name
    dir:  ~main_dir~/app1 #directory generate file
    template: ~template~/app.text #template for generate file
    file_name: main.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    generate_in: app #replace code @GenerateIn [key] in file with this job
    tags:
      #list of tag, that can executed by group of tag
      - structure
      - main
      - init route
      - init


  - name: end route in main #job name
    dir:  ~main_dir~/app1 #directory generate file
    template: ~template~/end_app.text #template for generate file
    file_name: main.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    generate_in: endApp #replace code @GenerateIn [key] in file with this job
    tags:
      #list of tag, that can executed by group of tag
      - structure
      - init
      - main
      - end_route

